# Change these first
owner: goosen999 # Your GitHub organization or username, where this repository lives
repo: evpstatus # The name of this repository

sites:
  - name: EVP main website
    url: https://www.elitevault.io
  - name: EVP buy website
    url: https://buy.elitevault.io
  - name: EVP vault website
    url: https://vault.elitevault.io

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /evpstatus
  logoUrl: https://elitevault.io/images/logo_new.png
  name: Elite Vault Protocol Status
  introTitle: "Your first step towards **sustainability** and **transparency**"
  introMessage: Elite Vault Protocol has a unique strategy to provide a sustainable project with **transparency**, **stable growth**, reasonable **passive income**, and **flexibility**.
  #This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
